# Generated by Django 5.2.17 on 2026-10-08 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=255)),
                ('ringkasan', models.TextField(blank=True, null=True)),
                ('gambar', models.CharField(blank=True, max_length=255, null=True)),
                ('tanggal', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Galeri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('gambar', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Sambutan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(default='Sambutan Koordinator Prodi', max_length=200)),
                ('isi', models.TextField()),
                ('nama_author', models.CharField(max_length=150)),
                ('foto', models.CharField(default='foto1.jpg', max_length=255)),
            ],
        ),
    ]
