# Generated by Django 5.2.17 on 2026-10-08 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Berita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('konten', models.TextField()),
                ('gambar', models.ImageField(upload_to='images/berita/')),
                ('tanggal', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_event', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('tanggal_pelaksanaan', models.DateField()),
                ('lokasi', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Galeri',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=200)),
                ('foto', models.ImageField(upload_to='images/galeri/')),
                ('tanggal', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kontak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alamat', models.TextField()),
                ('telepon', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Sambutan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(default='Sambutan Koordinator Prodi', max_length=200)),
                ('nama_koor', models.CharField(default='Dr. Intam Kurnia, M.Si.', max_length=150)),
                ('isi_sambutan', models.TextField()),
                ('foto', models.ImageField(upload_to='images/sambutan/')),
            ],
        ),
        migrations.CreateModel(
            name='SistemInformasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_sistem', models.CharField(max_length=150)),
                ('deskripsi', models.TextField()),
                ('link', models.URLField()),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/sistem/')),
            ],
        ),
    ]
