# Generated by Django 5.2.17 on 2026-10-08 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Akademik',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_informasi', models.CharField(max_length=200)),
                ('deskripsi', models.TextField()),
                ('file_dokumen', models.FileField(blank=True, null=True, upload_to='documents/akademik/')),
            ],
        ),
        migrations.CreateModel(
            name='Akreditasi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_akreditasi', models.CharField(default='Unggul (A)', max_length=50)),
                ('nomor_sk', models.CharField(max_length=100)),
                ('tanggal_kadaluarsa', models.DateField()),
                ('sertifikat', models.FileField(blank=True, null=True, upload_to='documents/akreditasi/')),
            ],
        ),
        migrations.CreateModel(
            name='StafDosen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=150)),
                ('jabatan', models.CharField(max_length=100)),
                ('nip_nidn', models.CharField(max_length=50)),
                ('foto', models.ImageField(upload_to='images/staf/')),
            ],
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='SistemInformasi',
        ),
        migrations.RemoveField(
            model_name='berita',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='sambutan',
            name='foto',
        ),
    ]
